# Combined workflow for documentation updates and static content deployment to GitHub Pages
name: Feature Branch Updates

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - f-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "features"
  cancel-in-progress: true

jobs:
  # First job: Update documentation/version
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Info (safe) 
        uses: actions/github-script@v6
        with:
          script: |
            const githubInfo = JSON.stringify(github.repos, null, 2)
            core.summary.addRaw("### GitHub Info\njson\n" + githubInfo + "\n\n")
            await core.summary.write()

   